name: 'Move trello to list'
description: 'Attach a trello card to a branch on creation'
inputs:
  trello-key:
    description: '(public) Trello auth key for account'
    required: true
  trello-token:
    description: 'secret Trello auth token for account'
    required: true
  board-id:
    description: "the id of the board the card is in"
    required: true
  list-id:
    description: "id of the list in which the card should be moved"
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'paperclip'  
  color: 'blue'
